# Generated by Django 4.2.6 on 2023-10-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_door_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
