# Generated by Django 4.2.6 on 2023-10-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_customer_delivery_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[("COMPLETE", "COMPLETE"), ("PENDING", "PENDING")],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
