# Generated by Django 4.2.6 on 2023-10-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_customer_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frame",
            name="type",
            field=models.CharField(
                choices=[
                    ("Small", "Small"),
                    ("Normal", "Normal"),
                    ("Medium", "Medium"),
                    ("Heavy", "Heavy"),
                    ("Door Without Clearence", "Door Without Clearence"),
                    ("Door With Clearence", "Door With Clearence"),
                ],
                max_length=50,
            ),
        ),
    ]
