# Generated by Django 4.2.6 on 2023-10-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_customer_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="google_location",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
