# Generated by Django 4.2.6 on 2023-10-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_customer_google_location_customer_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="door",
            name="glass_type_selection",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="glass_type_selection",
                to="app.glasstype",
            ),
        ),
        migrations.AddField(
            model_name="door",
            name="model_selection",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="model_selection",
                to="app.doormodel",
            ),
        ),
        migrations.CreateModel(
            name="SecondaryColour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_name", models.CharField(max_length=100)),
                (
                    "door",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.door"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrimaryColour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_name", models.CharField(max_length=100)),
                (
                    "door",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.door"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="door",
            name="primary_colour_selection",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_colour_selection",
                to="app.primarycolour",
            ),
        ),
        migrations.AddField(
            model_name="door",
            name="secondary_colour_selection",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secondary_colour_selection",
                to="app.secondarycolour",
            ),
        ),
    ]
