# Generated by Django 4.2.6 on 2023-10-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_door_glass_type_selection_door_model_selection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="advance_balance_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
