# Generated by Django 4.2.6 on 2023-10-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_customer_advance_balance_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="advance_balance_amount",
            new_name="balance_amount",
        ),
    ]
