# Generated by Django 4.2.6 on 2023-11-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_customer_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="door",
            name="finished",
            field=models.BooleanField(default=False),
        ),
    ]
