# Generated by Django 4.2.6 on 2023-11-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_door_finished"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoorBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("is_complete", models.BooleanField(default=False)),
                ("doors", models.ManyToManyField(to="app.door")),
            ],
        ),
    ]
