# Generated by Django 4.2.6 on 2023-11-07 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_doorbatch"),
    ]

    operations = [
        migrations.CreateModel(
            name="Remarks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_name", models.CharField(max_length=10000)),
                (
                    "door",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.door"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="door",
            name="remark_selection",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doors",
                to="app.remarks",
            ),
        ),
    ]
