# Generated by Django 4.2.6 on 2023-11-07 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_remarks_door_remark_selection"),
    ]

    operations = [
        migrations.RenameField(
            model_name="remarks",
            old_name="color_name",
            new_name="remarks",
        ),
    ]
