# Generated by Django 4.2.6 on 2023-11-24 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_rename_color_name_remarks_remarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_resin", models.FloatField()),
                ("cotting_resin", models.FloatField()),
                ("gelcoat", models.FloatField()),
                ("pigment", models.FloatField()),
                ("putty_total", models.FloatField()),
                ("putty_resin", models.FloatField()),
                ("cilica_pwdr", models.FloatField()),
                ("chalk_pwdr", models.FloatField()),
                (
                    "door",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_requirement",
                        to="app.door",
                    ),
                ),
            ],
        ),
    ]
