# Generated by Django 4.2.6 on 2024-11-27 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_materialrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.AlterField(
            model_name='door',
            name='door_open_selection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.dooropen'),
        ),
        migrations.AlterField(
            model_name='door',
            name='finish_selection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.finish'),
        ),
        migrations.AlterField(
            model_name='door',
            name='frame_selection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.frame'),
        ),
        migrations.AlterField(
            model_name='door',
            name='glass_type_selection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glass_type_selection', to='app.glasstype'),
        ),
        migrations.AlterField(
            model_name='door',
            name='hinge_selection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hinge'),
        ),
        migrations.AlterField(
            model_name='door',
            name='lock_selection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lock'),
        ),
        migrations.AlterField(
            model_name='door',
            name='measurement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.measurement'),
        ),
        migrations.AlterField(
            model_name='door',
            name='model_selection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_selection', to='app.doormodel'),
        ),
        migrations.AlterField(
            model_name='door',
            name='primary_colour_selection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_colour_selection', to='app.primarycolour'),
        ),
        migrations.AlterField(
            model_name='door',
            name='remark_selection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='app.remarks'),
        ),
        migrations.AlterField(
            model_name='door',
            name='secondary_colour_selection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_colour_selection', to='app.secondarycolour'),
        ),
    ]
